[package]
name = "nmpurge-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-watch = "8.4.0"
fd-find = "8.7.0"
fs_extra = "1.3.0"
human_bytes = "0.4.1"
